### ISSUE TITLE
sharing of your Gerber viewer project

### ISSUE THREAD

**Issue by aeonSolutions** [xingrz/GerberViewer#2]
Hi @xingrz 
great work!
just to let you know I'm sharing 😍 and adding a link to your project on my Github. 
You can find it here:
[https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/DIY-Maker/README.md](https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/DIY-Maker/README.md)

👍

**Comment by xingrz** [comment]
😄 Thank you!
